{% set name = "emg3d" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccb6bc89c3a731bfdf88f97a28c6b08a4337e9d09800a15b7f043734e931f88f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  preserve_egg_dir: true

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - empymod >=2.0.0
    - numba >=0.45.0
    - numpy
    - python >=3.7
    - scipy >=1.4.0

test:
  imports:
    - emg3d

about:
  home: https://empymod.github.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A multigrid solver for 3D electromagnetic diffusion.
  description: |
    The modeller emg3d is a multigrid solver for 3D EM diffusion with tri-axial
    electrical anisotropy. The matrix-free solver can be used as main solver or
    as preconditioner for Krylov subspace methods, and the governing equations
    are discretized on a staggered Yee grid.
  doc_url: https://emg3d.readthedocs.io/
  dev_url: https://github.com/empymod/emg3d

extra:
  recipe-maintainers:
    - prisae
