{% set name = "emg3d" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f2bf7ccc21583cdc5aecb7c077e5f823d9e7981db661bae80ef95761da25b2e5
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - emg3d=emg3d.cli.main:main

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - numba >=0.45.0
    - python >=3.7
    - scipy >=1.4.0

test:
  imports:
    - emg3d

about:
  home: https://emsig.xyz
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A multigrid solver for 3D electromagnetic diffusion.
  description: |
    The modeller emg3d is a multigrid solver for 3D EM diffusion with tri-axial
    electrical anisotropy. The matrix-free solver can be used as main solver or
    as preconditioner for Krylov subspace methods, and the governing equations
    are discretized on a staggered Yee grid.
  doc_url: https://emg3d.emsig.xyz
  dev_url: https://github.com/emsig/emg3d

extra:
  recipe-maintainers:
    - prisae
